---
- name: Installation de Java, Tomcat et démarrage du service
  hosts: all
  become: yes

  tasks:
    - name: Installation d'OpenJDK Java 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Installation de Tomcat
      apt:
        name: tomcat9
        state: present

    - name: Démarrage du service Tomcat
      service:
        name: tomcat9
        state: started
        enabled: yes
