---
- name: Vérifier si Maven est déjà installé
  hosts: all
  become: yes
  tasks:
    - name: Vérifier si Maven est déjà installé
      command: mvn --version
      register: mvn_version_output
      ignore_errors: yes

    - name: Afficher la version de Maven si déjà installée
      debug:
        msg: "Maven est déjà installé : {{ mvn_version_output.stdout }}"
      when: mvn_version_output.rc == 0

    - name: Installer Maven si ce n'est pas déjà fait
      package:
        name: maven
        state: present
      when: mvn_version_output.rc != 0
